//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacje
    {
        public int id_rezerwacji { get; set; }
        public int id_klienta { get; set; }
        public System.DateTime data_rezerwacji { get; set; }
        public int id_pokoju { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Pokoje Pokoje { get; set; }
    }
}
